---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: flight-ingress
  namespace: apps
  annotations:
    hub.traefik.io/api: flight-api
spec:
  routes:
    - match: Host(`api.docker.localhost`) && PathPrefix(`/flights`)
      kind: Rule
      services:
        - name: flight-app
          port: 3000
---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: flight-api
  namespace: apps
  labels:
    area: flights
    module: erp
spec:
  openApiSpec:
    path: /openapi.yaml
