---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: employee-ingress
  namespace: apps
  annotations:
    hub.traefik.io/api: employee-api
spec:
  routes:
    - match: Host(`api.docker.localhost`) && PathPrefix(`/employees`)
      kind: Rule
      services:
        - name: employee-app
          port: 3000
---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: employee-api
  namespace: apps
  labels:
    area: employee
    module: crm
spec:
  openApiSpec:
    path: /openapi.yaml