---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-hub
  namespace: traefik-hub
spec:
  releaseName: traefik-hub
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik-hub
  interval: 50m
  install:
    remediation:
      retries: 15
  upgrade:
    crds: CreateReplace
  values:
    hub:
      token: hub-agent-token
      apimanagement:
        enabled: true

    additionalArguments:
      - "--providers.kubernetescrd.allowCrossNamespace=true"
      - "--providers.kubernetesingress.allowexternalnameservices=true"
      - "--providers.kubernetescrd.allowexternalnameservices=true"

    image:
      registry: ghcr.io
      repository: traefik/traefik-hub
      tag: v3.4.0
      pullPolicy: Always

    ingressRoute:
      dashboard:
        enabled: true

    ports:
      web:
        nodePort: 30000
      websecure:
        nodePort: 30001
      metrics:
        port: 9100

    metrics:
      prometheus: null
      otlp:
        enabled: true
        http:
          enabled: true
          endpoint: "http://prometheus.monitoring:9090/api/v1/otlp/v1/metrics"

    service:
      type: LoadBalancer
      # Needed on local Kind k8s cluster.
      # Can be removed or customized as needed on other k8s cluster.
