---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: customer-api
  namespace: apps
  labels:
    area: customers
    module: crm
spec:
  openApiSpec:
    path: /openapi.yaml
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: customers-ingress
  namespace: apps
  annotations:
    hub.traefik.io/api: customer-api
spec:
  routes:
    - match: Host(`api.docker.localhost`) && PathPrefix(`/customers`)
      kind: Rule
      services:
        - name: customer-app
          port: 3000