apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - pv.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - behavior: create
    files:
      - grafana-dashboards/hub/traefik-standalone.json
    name: grafana-hub-dashboards
    namespace: monitoring
  - behavior: create
    files:
      - grafana-dashboards/flux/control-plane.json
    name: grafana-flux-dashboards
    namespace: monitoring
